permissions:
    statuses: write

on: [pull_request, workflow_dispatch]

jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
            # To use this action,
            # you must check out the repository
            - name: Checkout
              uses: actions/checkout@v3
            - run: |
                BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
                echo "$BRANCH"
